openapi: "3.0.0"
info:
  title: Printer Group  API
  description: THE API WHICH WIll PERFORM PRINTER GROUP CRUD OPERATIONS.
  version: 1.0.0

tags: 
 name: PrinterGroups
 name: PrinterGroupAssignment

paths:
  /printer-groups:
    post:
      summary: Create PrinterGroups!
      tags: [PrinterGroups]
      description: Create A Printer Group.      
      requestBody:
        required: true
        content:
          application/json:
            schema: 
                type: object
                properties:
                  title:
                    type: string
                  description:
                    type: string
                  printType:
                    type: integer
                    enum:
                      - 1
                      - 2     
                  triggers:    
                    type: array 
                    items: 
                      type: object 
                      properties:
                        trigger:
                          type: integer
                          enum:
                            - 1
                            - 2
                            - 3
                        orderType:
                          type: integer
                          enum:
                            - 1
                            - 2            
      responses:
        200:
          description: The PrinterGroupTrigger is Created!
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  description:
                    type: string
                  printType:
                    type: integer
                  status:
                    type: string 
        400:
          description: Bad request! 
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string     
        500:
          description: Internal Server Error! 
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string                                
    get:
        summary: Get PrinterGroups!
        tags: [PrinterGroups]
        description: Get All PrinterGroups.    
        parameters:
          - in: query
            name: status
            schema:
              type: integer
              enum:
                - 0
                - 1 
        responses:
          200:
            description: The PrinterGroups List Is!
            content:
              application/json:
                schema: 
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    description:
                      type: string
                    printType:
                      type: integer
                    printerCount:
                      type: integer  
                    updatedAt: 
                      type: integer   
                    createdAt:
                      type: integer
                    createdBy:
                      type: integer
                    updatedBy:
                      type: integer    
                    status:
                      type: boolean  
          204:
            description: No Content! 
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    code:
                      type: string 
          500:
            description: Internal Server Error! 
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    code:
                      type: string
  /printer-groups/{printerGroupId}:                    
    get:
        summary: Fetch One PrinterGroup!
        tags: [PrinterGroups]
        description: Fetch One PrinterGroup with Triggers.
        parameters:
          - in: path
            name: printerGroupId
            schema:
              type: integer
            # required: true      
        responses:
          200:
            description: The PrinterGroupTriggers List Is!
            content:
              application/json:
                schema: 
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    description:
                      type: string
                    printType:
                      type: integer
                    printerCount:
                      type: integer 
                    updatedAt: 
                      type: integer   
                    createdAt:
                      type: integer
                    createdBy:
                      type: integer
                    updatedBy:
                      type: integer   
                    status:
                      type: boolean   
                    triggers:    
                      type: array 
                      items: 
                        type: object 
                        properties:
                          id:
                            type: integer
                          printerGroupId:
                            type: integer  
                          trigger:
                            type: integer
                          orderType:
                            type: integer
                          updatedAt: 
                            type: integer   
                          createdAt:
                            type: integer
                          createdBy:
                            type: integer
                          updatedBy:
                            type: integer
          400:
            description: Bad Request! 
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    code:
                      type: string   
          500:
            description: Internal Server Error! 
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    code:
                      type: string                                                                             
    put:
      summary: Update PrinterGroups!
      tags: [PrinterGroups]
      description: Update A PrinterGroups.
      parameters:
        - in: path
          name: printerGroupId
          schema:
            type: string
          # required: true  
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string 
                printType:
                  type: integer
                  enum:
                    - 1
                    - 2         
      responses:
        200:
          description: The PrinterGroups is updated!
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string    
        400:
          description: Bad Request! 
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string             
        500:
          description: Internal Server Error! 
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string            
  /printer-groups/trigger/{printerGroupTriggerId}:
    put:
      summary: Update PrinterGroupTriggers!
      tags: [PrinterGroups]
      description: Update An PrinterGroupTriggers.
      parameters:
        - in: path
          name: printerGroupTriggerId
          schema:
            type: integer
          # required: true  
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                trigger:
                  type: integer
                  enum:
                    - 1
                    - 2
                    - 3
                orderType:
                  type: integer
                  enum:
                    - 1
                    - 2      
      responses:
        200:
          description: The PrinterGroups is updated!
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string
        400:
          description: Bad Request! 
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string                        
        500:
          description: Internal Server Error! 
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
  /device/printer/{printerId}/assign/printerGroups:
    post:
      summary: Assign PrinterGroups!
      tags: [PrinterGroupAssignment]
      description: Assign PrinterGroups to Printer. 
      parameters:
        - in: path
          name: printerId
          schema:
            type: integer
          # required: true     
      requestBody:
        required: true
        content:
          application/json:
            schema: 
                type: object
                properties:     
                  printerGroupId:    
                    type: array
                    items:
                      type: integer
                    example: 
                      - 1
                      - 2
                      - 3          
      responses:
        200:
          description: The PrinterGroups is UnAssigned!
          content:
            application/json:
              schema: 
                type: object
                properties:     
                  data:    
                    type: object 
                    properties:
                      printerGroupIds:
                        type: array       
                        items: 
                          type: integer 
                        example: 
                          - 1
                          - 2
                          - 3  
                  message:
                    type: string
        400:
          description: Bad request! 
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string     
        500:
          description: Internal Server Error! 
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
  /device/printer/{printerId}/unAssign/printerGroups:
    put:
      summary: UnAssign PrinterGroups!
      tags: [PrinterGroupAssignment]
      description: UnAssign PrinterGroups to Printer.  
      parameters:
        - in: path
          name: printerId
          schema:
            type: integer
          # required: true   
      requestBody:
        required: true
        content:
          application/json:
            schema: 
                type: object
                properties:     
                  printerGroupId:    
                    type: array 
                    items: 
                      type: integer 
                    example: 
                      - 1
                      - 2
                      - 3              
      responses:
        200:
          description: The PrinterGroups is UnAssigned!
          content:
            application/json:
              schema: 
                type: object
                properties:     
                  data:    
                    type: object 
                    properties:
                      printerGroupIds:
                        type: array       
                        items: 
                          type: integer 
                        example: 
                          - 1
                          - 2
                          - 3  
                  message:
                    type: string        
        400:
          description: Bad request! 
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string     
        500:
          description: Internal Server Error! 
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string 
  /device/printer/{printerId}/assign/printerGroup/{printerGroupId}:
    post:
      summary: Assign  PrinterGroup!
      tags: [PrinterGroupAssignment]
      description: Assign Printer to PrinterGroup. 
      parameters:
        - in: path
          name: printerId
          schema:
            type: integer
          # required: true
        - in: path
          name: printerGroupId
          schema:
            type: integer
          # required: true                
      responses:
        200:
          description: The PrinterGroups is UnAssigned!
          content:
            application/json:
              schema: 
                type: object
                properties:     
                  data:    
                    type: object 
                    properties:
                      printerGroupId:
                        type: integer  
                  message:
                    type: string 
        400:
          description: Bad request! 
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string     
        500:
          description: Internal Server Error! 
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string 
  /device/printer/{printerId}/unAssign/printerGroup/{printerGroupId}:
    delete:
      summary: UnAssign PrinterGroup!
      tags: [PrinterGroupAssignment]
      description: UnAssign PrinterGroup to Printer.  
      parameters:
        - in: path
          name: printerId
          schema:
            type: integer
          # required: true  
        - in: path
          name: printerGroupId
          schema:
            type: integer
          # required: true                 
      responses:
        200:
          description: The PrinterGroups is UnAssigned!
          content:
            application/json:
              schema: 
                type: object
                properties:     
                  data:    
                    type: object 
                    properties:
                      printerGroupId:
                        type: integer  
                  message:
                    type: string 
        400:
          description: Bad request! 
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string     
        500:
          description: Internal Server Error! 
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string  
                                                                         
                                                                        
                                     
